version: '3'
networks:
  app-tier:
    driver: bridge
volumes:
  todo-pgdata:
  redis_data:
services:
  todo_postgres_local:
    container_name: todo_postgres_local
    image: postgres:11
    ports:
      - "7011:5432"
    volumes:
      - todo-pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - app-tier
  todo_redis:
    container_name: todo_redis
    image: 'bitnami/redis:latest'
    volumes:
      - redis_data:/bitnami/redis/data
    env_file:
      - .env
    ports:
      - 5103:6379
    networks:
      - app-tier
  adminer:
    container_name: todo_adminer_local
    image: adminer
    depends_on:
      - todo_postgres_local
    # restart: always
    ports:
      - 7012:8080
    networks:
      - app-tier