export enum RATING_FEEDBACK {
  DIFFICULT_TO_USE = 'DIFFICULT_TO_USE',
  NORMAL = 'NORMAL',
  EASY_TO_YOU = 'EASY_TO_YOU'
}

export type RATING_FEEDBACK_TYPE = RATING_FEEDBACK.DIFFICULT_TO_USE | RATING_FEEDBACK.NORMAL | RATING_FEEDBACK.EASY_TO_YOU;